### ISSUE TITLE
Cannot get executable file for macOS

### ISSUE THREAD

**Issue by kenichikat** [virtualstaticvoid/asdf-aws-vault#1]
hi
I made an Issue because it doesn't seem to work well on macOS.

aws-vault is a text file with the content “Not Found%”.

```
asdf list aws-vault
 *7.2.0

cat ~/.asdf/installs/aws-vault/7.2.0/bin/aws-vault
Not Found%
```

Because of the “.dmg” extension in the macOS download URL, the executable file cannot be downloaded.
Also, since it is distributed in dmg format, it is not likely to work even if you place it directly.

https://github.com/99designs/aws-vault/releases/

**Comment by virtualstaticvoid** [comment]
It appears that the [`karancode/asdf-aws-vault` plugin](https://github.com/karancode/asdf-aws-vault) supports MacOS.
